name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: python -m pip install --upgrade pip && pip install -r requirements.txt
      - name: Lint (black)
        run: black --check .
      - name: Lint (ruff)
        run: ruff check .
      - name: Run tests
        run: pytest -q
      - name: Validate sample report against schema
        run: python scripts/validate_report.py samples/sample_report.json schemas/report-schema-1.0.0.json
