name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Lint (black)
        run: black --check .
      
      - name: Lint (ruff)
        run: ruff check .
      
      - name: Security scan (bandit)
        run: bandit -r agent/ -f txt || true
        continue-on-error: true
      
      - name: Run tests with coverage
        run: pytest --cov=agent --cov-report=term --cov-report=xml --cov-report=html -v
      
      - name: Upload coverage to artifacts
        uses: actions/upload-artifact@v3
        if: matrix.python-version == '3.11'
        with:
          name: coverage-report
          path: |
            htmlcov/
            coverage.xml
      
      - name: Check coverage threshold
        run: |
          coverage report --fail-under=35
      
      - name: Validate sample report against schema
        run: python scripts/validate_report.py samples/sample_report.json schemas/report-schema-1.0.0.json
